 #!/bin/bash
 #PBS -q workq
 #PBS -A loni_lbmtest
 #PBS -l nodes=6:ppn=20
 #PBS -l walltime=72:00:00
 #PBS -o /scratch/saurav/plasma
 #PBS -j oe 
 #PBS -N parPlasma
 
 date

 module load python/3.5.2-anaconda-tensorflow
 
 # Set some handy environment variables.
 export HOME_DIR=/home/saurav/plasma
 export foldernamee=20cpus
 export WORK_DIR=/scratch/saurav/plasma/20cpus
 export NPROCS=`wc -l $PBS_NODEFILE |gawk '//{print $1}'`
 
 mkdir -p $WORK_DIR/
 rm -rf $WORK_DIR/plasma/*
 cp -r $HOME_DIR/  $WORK_DIR/
 cd $WORK_DIR/
 mpirun -machinefile $PBS_NODEFILE -np $NPROCS python $WORK_DIR/parallel.py
 cp -r  $WORK_DIR $HOME_DIR
 date

